import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-add-user',
  templateUrl: './add-user.component.html',
  styleUrls: ['./add-user.component.scss']
})
export class AddUserComponent implements OnInit {

  agencies: string[] = [
    "",
"ARIANA",
"AV.LIBERTE TUNIS",
"Bab Jedid",
"Bakalta",
"BARCELONE",
"Barraket Essahel",
"Beja",
"Ben Arous",
"Ben Gardane",
"Bir Lahmar",
"Bou Argoub",
"Bou Ficha",
"Boumerdes",
"BVD 5 AOUT SFAX",
"CA AVENUE PARIS",
"CA BELVEDERE",
"CA CHARGUIA",
"CA MEGRINE",
"CA NEAPOLIS",
"CA SOUSSE CENTRE",
"Dar Chaabane",
"Den Den",
"Djerba El May",
"Djerba Houmet Souk",
"Djerba Midoun",
"Douz",
"El Aghailiba Kairouan",
"El Djem",
"El Ghazela",
"El Manar",
"El Mechtel",
"El Oued",
"Ennasr II",
"ETTADHAMEN",
"Fouchana",
"Gabes",
"Gabes El Menzel",
"Gafsa Place d'Afrique",
"Gafsa Place du Marché",
"Hammam Lif",
"Hammamet",
"Hammam Sousse",
"Hedi Nouira",
"Jebel Abderrahman",
"Jemmal",
"Jendouba",
"Jerba Midoun",
"Jebniana",
"Kairouan",
"Kebili",
"Ksar Hellal",
"La Goulette",
"La Marsa",
"Le Bardo",
"Le Kef",
"Le Kram",
"Les Berges du Lac",
"Les Jardins du Lac",
"Les Roseraies",
"Mahdia",
"MED 5",
"Medenine",
"Menzel Bourguiba",
"Menzel Jemil",
"Moknine",
"Monastir",
"Montplaisir",
"M'saken",
"Nabeul",
"Nafta",
"Nouvelle Ariana",
"Oued Ellil",
"PLACE M.BEY TUNIS",
"Rades",
"Redeyef",
"Remarda",
"RUE MONGI SLIM",
"Sidi Bou Said",
"Sidi Bouzid",
"Sidi Thabet",
"Siliana",
"Soliman",
"Souk El Ahad",
"Souk El Jemaa",
"Soukra",
"Sousse Bab Jedid",
"Sousse Centre",
"Sousse Erriadh",
"Sousse H.Bourguiba",
"Sousse Sahloul",
"Sousse Senghor",
"Sfax",
"Sfax El Bousten",
"Sfax El Jadida",
"Sfax Habib Thameur",
"Sfax Zephir",
"Tabarka",
"Tajerouine",
"Tataouine",
"Teboulba",
"Tozeur",
"Zarmdine",
"Zarzis",
"Zarath Gabes",
"Z FRANCHE",
"Le Passage",
"Belvedere II 106",
"Avenue de Paris II",
"Yesmine El Hammamet",
  ];

  ngOnInit(): void {
  }

}
